# Wikipedia airborne-radar knowledge graph with Neo4j

This notebook uses the repository's `combat_id_calibration.graph_ingest` module to build a local Neo4j knowledge graph from Wikipedia pages for the MiG-29, the Ukrainian Air Force, the Russian Air Force, the Bars radar, and representative Russian or Israeli airborne radars.

The existing ingestion module performs the core workflow: fetch Wikipedia HTML, extract readable text, chunk documents, ask a local Ollama model to return auditable JSON facts, optionally write facts to JSONL, and populate Neo4j with `Entity`, `Source`, `FACT`, and `MENTIONED_IN` records.

> Wikipedia is a convenient public source, but it is not authoritative. Review `facts-jsonl` output before using extracted relationships for combat-identification scoring or calibration.

## 1. Install and runtime prerequisites

From the repository root, install the graph extra and make sure Ollama is running with the configured model:

```bash
python -m pip install -e .[graph]
ollama pull qwen3.5:9b
ollama serve
```

If your notebook starts in `notebooks/`, the setup cell below adds the repository root to `sys.path` so it imports the local module under development.

In [1]:
from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path.cwd().resolve()
if REPO_ROOT.name == 'notebooks':
    REPO_ROOT = REPO_ROOT.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from combat_id_calibration.graph_ingest import (
    DEFAULT_MODEL,
    DEFAULT_OLLAMA_URL,
    extract_facts,
    load_documents,
    populate_neo4j,
    write_facts_jsonl,
)

## 2. Configure Wikipedia sources

The first four URLs satisfy the explicitly requested pages. The remaining URLs add representative Russian and Israeli airborne radar pages so the resulting graph has more radar-specific evidence.

In [2]:
NEO4J_URI = 'bolt://localhost:7687'
NEO4J_USER = 'neo4j'
NEO4J_PASSWORD = "password123"  # replace with your Neo4j password before running the population cell
NEO4J_DATABASE = None
FACTS_JSONL = REPO_ROOT / 'wikipedia_airborne_radars_facts.jsonl'
MODEL = DEFAULT_MODEL
OLLAMA_URL = DEFAULT_OLLAMA_URL
MAX_CHARS = 6000
OVERLAP = 500

WIKIPEDIA_URLS = [
    'https://en.wikipedia.org/wiki/Mikoyan_MiG-29',
    'https://en.wikipedia.org/wiki/Ukrainian_Air_Force',
    'https://en.wikipedia.org/wiki/Russian_Air_Force',
    'https://en.wikipedia.org/wiki/Bars_radar',

    # Additional Russian airborne radars
    'https://en.wikipedia.org/wiki/Irbis-E',
    'https://en.wikipedia.org/wiki/Zhuk_(radar)',
    'https://en.wikipedia.org/wiki/Mech_radar',
    # Additional Israeli airborne radars
    'https://en.wikipedia.org/wiki/EL/M-2032',
    'https://en.wikipedia.org/wiki/EL/W-2085',
    'https://en.wikipedia.org/wiki/EL/M-2052',
]

In [3]:
WIKIPEDIA_URLS_2 = ['https://en.wikipedia.org/wiki/Sukhoi_Su-27',
                    'https://en.wikipedia.org/wiki/McDonnell_Douglas_F-15_Eagle',
                    'https://en.wikipedia.org/wiki/Eurofighter_Typhoon',
                    'https://en.wikipedia.org/wiki/R-77',
                    'https://en.wikipedia.org/wiki/Euroradar_CAPTOR'
                    ]

## 3. Load Wikipedia documents with `graph_ingest.py`

`load_documents` delegates each Wikipedia URL to `read_wikipedia`, preserving a deterministic source ID, source type, locator URL, article title, and extracted article text.

In [4]:


documents_2 = load_documents(pdf_paths=[], wikipedia_urls=WIKIPEDIA_URLS_2)
print(f'Loaded {len(documents_2)} Wikipedia documents')
for document in documents_2:
    print(f'- {document.title}: {len(document.text):,} characters from {document.locator}')

https://en.wikipedia.org/wiki/Sukhoi_Su-27
https://en.wikipedia.org/wiki/McDonnell_Douglas_F-15_Eagle
https://en.wikipedia.org/wiki/Eurofighter_Typhoon
https://en.wikipedia.org/wiki/R-77
https://en.wikipedia.org/wiki/Euroradar_CAPTOR
Loaded 5 Wikipedia documents
- Sukhoi Su-27: 85,407 characters from https://en.wikipedia.org/wiki/Sukhoi_Su-27
- McDonnell Douglas F-15 Eagle: 108,200 characters from https://en.wikipedia.org/wiki/McDonnell_Douglas_F-15_Eagle
- Eurofighter Typhoon: 155,830 characters from https://en.wikipedia.org/wiki/Eurofighter_Typhoon
- R-77: 21,727 characters from https://en.wikipedia.org/wiki/R-77
- Euroradar CAPTOR: 41,847 characters from https://en.wikipedia.org/wiki/Euroradar_CAPTOR

## 4. Extract auditable facts with Ollama

This cell calls the repository ingestion module's `extract_facts`, which chunks each source and applies the module's constrained JSON extraction prompt. Keep `FACTS_JSONL` under review; it is the audit artifact to inspect before trusting the Neo4j graph.

In [ ]:
facts = extract_facts(
    documents_2,
    model=MODEL,
    ollama_url=OLLAMA_URL,
    max_chars=1000,
    overlap=200,
)
write_facts_jsonl(facts, FACTS_JSONL)
print(f'Extracted {len(facts)} facts')
print(f'Wrote review file: {FACTS_JSONL}')

[graph-ingest] starting fact extraction with model='qwen3.5:9b', ollama_url='http://localhost:11434', max_chars=1000, overlap=200
[graph-ingest] document 1: title='Sukhoi Su-27', source_id=0a6672b89f918010, type=wikipedia, text_chars=85407, chunks=105
[graph-ingest] document 1 chunk 1/105: sending 1000 chars to Ollama
[graph-ingest] document 1 chunk 1/105: received 12 chars; preview='{"facts":[]}'
[graph-ingest] document 1 chunk 1/105: JSON candidate 1 contains facts=0
[graph-ingest] document 1 chunk 1/105: normalized 0 fact(s); skipped 0 invalid item(s)
[graph-ingest] document 1 chunk 1/105: added 0 fact(s)
[graph-ingest] document 1 chunk 2/105: sending 1000 chars to Ollama
[graph-ingest] document 1 chunk 2/105: received 12 chars; preview='{"facts":[]}'
[graph-ingest] document 1 chunk 2/105: JSON candidate 1 contains facts=0
[graph-ingest] document 1 chunk 2/105: normalized 0 fact(s); skipped 0 invalid item(s)
[graph-ingest] document 1 chunk 2/105: added 0 fact(s)
[graph-ingest] document 1 chunk 3/105: sending 1000 chars to Ollama
[graph-ingest] document 1 chunk 3/105: received 1722 chars; preview='{"facts":[{"subject":"Sukhoi Su-27","predicate":"IS_A","object":"fighter aircraft","evidence":"is a Soviet twin-engine supersonic supermaneuverable fighter aircraft","confidence":1.0},{"subject":"Sukhoi Su-27","predicate":"HAS_SIGNATURE","object":"NATO reporting name: Flanker","evidence":"NATO repor'
[graph-ingest] document 1 chunk 3/105: JSON candidate 1 contains facts=10
[graph-ingest] document 1 chunk 3/105: normalized 10 fact(s); skipped 0 invalid item(s)
[graph-ingest] document 1 chunk 3/105: added 10 fact(s)
[graph-ingest] document 1 chunk 4/105: sending 1000 chars to Ollama
[graph-ingest] document 1 chunk 4/105: received 1723 chars; preview='{"facts":[{"subject":"Sukhoi Su-27","predicate":"DESIGNED_BY","object":"Sukhoi","confidence":1.0},{"subject":"Sukhoi Su-27","predicate":"COMPETES_AGAINST","object":["Grumman F-14 Tomcat","McDonnell Douglas F-15 Eagle"],"confidence":1.0},{"subject":"Sukhoi Su-27","predicate":"HAS_RANGE","object":"3,5'
[graph-ingest] document 1 chunk 4/105: JSON candidate 1 contains facts=14
[graph-ingest] document 1 chunk 4/105: normalized 14 fact(s); skipped 0 invalid item(s)
[graph-ingest] document 1 chunk 4/105: added 14 fact(s)
[graph-ingest] document 1 chunk 5/105: sending 1000 chars to Ollama
[graph-ingest] document 1 chunk 5/105: received 2191 chars; preview='{"facts":[{"subject":"Sukhoi Su-27","predicate":"DEVELOPED_INTO_FAMILY_OF_AIRCRAFT","object":"true","evidence":"The Su-27 was developed into a family of aircraft; these include the Su-30, Su-33, Su-34, and Su-35.","confidence":1.0},{"subject":"Su-30","predicate":"VARIANT_OF","object":"Sukhoi Su-27",'
[graph-ingest] document 1 chunk 5/105: JSON candidate 1 contains facts=12
[graph-ingest] document 1 chunk 5/105: normalized 12 fact(s); skipped 0 invalid item(s)
[graph-ingest] document 1 chunk 5/105: added 12 fact(s)
[graph-ingest] document 1 chunk 6/105: sending 1000 chars to Ollama
[graph-ingest] document 1 chunk 6/105: received 187 chars; preview='{"facts":[{"subject":"Perspektivnyy Frontovoy Istrebitel","predicate":"ALSO_KNOWN_AS","object":"PFI","evidence":"literally \\"Prospective Frontline Fighter\\",\\"confidence\\":1.0},{"  \\n\\n\\n}]}'
[graph-ingest] document 1 chunk 6/105: JSON candidate 1 contains facts=1
[graph-ingest] document 1 chunk 6/105: normalized 1 fact(s); skipped 0 invalid item(s)
[graph-ingest] document 1 chunk 6/105: added 1 fact(s)
[graph-ingest] document 1 chunk 7/105: sending 1000 chars to Ollama
[graph-ingest] document 1 chunk 7/105: received 2683 chars; preview='{\\n"facts":[\\n{"subject":"Mikoyan MiG-29","predicate":"VARIANT_OF","object":"LPFI","evidence":"the LPFI program resulted in the Mikoyan MiG-29 , a relatively short-range tactical fighter","confidence":1.0},\\n{"subject":"Sukhoi OKB","predicate":"ASSIGNED_MISSION_TO","object":"TPFI","evidence":"The TPFI '
[graph-ingest] document 1 chunk 7/105: JSON candidate 1 contains facts=12
[graph-ingest] document 1 chunk 7/105: normalized 12 fact(s); skipped 0 invalid item(s)
[graph-ingest] document 1 chunk 7/105: added 12 fact(s)
[graph-ingest] document 1 chunk 8/105: sending 1000 chars to Ollama

## 5. Populate Neo4j with `graph_ingest.py`

`populate_neo4j` creates the same schema used by the repository CLI:

- `Entity(id, name)`
- `Source(id, source_type, locator)`
- `FACT(predicate, source_id, evidence, confidence)`
- `MENTIONED_IN`

If you want a clean graph, clear the target Neo4j database before running this population cell.

If `NEO4J_PASSWORD` is left as `None` or an empty string, the population cell stops before opening a Neo4j driver and asks you to set the password.

In [8]:
NEO4J_USER = 'neo4j'
NEO4J_PASSWORD = "password123"

populate_neo4j(facts, NEO4J_URI, NEO4J_USER, NEO4J_PASSWORD, NEO4J_DATABASE)
print(f'Populated Neo4j database: {NEO4J_URI}')

Populated Neo4j database: bolt://localhost:7687

## 6. Query examples

The queries below inspect the graph generated by `populate_neo4j`. They intentionally work with the generic `Entity`/`FACT` schema from `graph_ingest.py` instead of introducing a separate notebook-only schema.

In [9]:
import pandas as pd
from neo4j import GraphDatabase

driver = GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USER, NEO4J_PASSWORD))
session_kwargs = {'database': NEO4J_DATABASE} if NEO4J_DATABASE else {}
session = driver.session(**session_kwargs)

def show(query: str, params: dict | None = None):
    result = session.run(query, params or {})
    rows = pd.DataFrame([record.data() for record in result])
    display(rows)
    return rows

In [10]:
show('''
MATCH (source:Source)
RETURN source.source_type AS source_type, source.locator AS locator
ORDER BY locator
''')

  source_type                                            locator
0   wikipedia           https://en.wikipedia.org/wiki/Bars_radar
1   wikipedia            https://en.wikipedia.org/wiki/EL/M-2032
2   wikipedia            https://en.wikipedia.org/wiki/EL/M-2052
3   wikipedia            https://en.wikipedia.org/wiki/EL/W-2085
4   wikipedia              https://en.wikipedia.org/wiki/Irbis-E
5   wikipedia           https://en.wikipedia.org/wiki/Mech_radar
6   wikipedia       https://en.wikipedia.org/wiki/Mikoyan_MiG-29
7   wikipedia    https://en.wikipedia.org/wiki/Russian_Air_Force
8   wikipedia  https://en.wikipedia.org/wiki/Ukrainian_Air_Force
9   wikipedia         https://en.wikipedia.org/wiki/Zhuk_(radar)

  source_type                                            locator
0   wikipedia           https://en.wikipedia.org/wiki/Bars_radar
1   wikipedia            https://en.wikipedia.org/wiki/EL/M-2032
2   wikipedia            https://en.wikipedia.org/wiki/EL/M-2052
3   wikipedia            https://en.wikipedia.org/wiki/EL/W-2085
4   wikipedia              https://en.wikipedia.org/wiki/Irbis-E
5   wikipedia           https://en.wikipedia.org/wiki/Mech_radar
6   wikipedia       https://en.wikipedia.org/wiki/Mikoyan_MiG-29
7   wikipedia    https://en.wikipedia.org/wiki/Russian_Air_Force
8   wikipedia  https://en.wikipedia.org/wiki/Ukrainian_Air_Force
9   wikipedia         https://en.wikipedia.org/wiki/Zhuk_(radar)

In [11]:
show('''
MATCH (subject:Entity)-[fact:FACT]->(object:Entity)
WHERE lower(subject.name) CONTAINS 'radar'
   OR lower(object.name) CONTAINS 'radar'
   OR lower(fact.predicate) CONTAINS 'sensor'
RETURN subject.name AS subject, fact.predicate AS predicate, object.name AS object,
       fact.confidence AS confidence, fact.evidence AS evidence
ORDER BY confidence DESC
LIMIT 50
''')

,subject,predicate,object,confidence,evidence
0,Bars radar family,CONTAINS_RADAR_MODEL,N035 Irbis-E,1.0,The most powerful radar of Bars radar family
1,Bars radar MAP MODE,HAS_RESOLUTION_LIMITATION,10 meters,1.0,with a maximum resolution of 10 meters
2,Bars radar,HAS_AIR_TO_AIR_DETECTION_RANGE_EARLY_WARNING_ROLE,over 400 km,1.0,The maximum air-to-air detection range is over...
3,Bars radar,HAS_AIR_TO_SURFACE_MODES_COUNT,five air-to-ground modes and four maritime modes,1.0,"For air-to-surface mode, the N011 has five air..."
4,N011M,IS_A,Bars radar family member,1.0,second member of the Bars radar family is the ...
5,Bars radar,HAS_MODE,"mapping mode using real beam, doppler beam sha...",1.0,Bars also features a mapping mode using either...
6,N011M,IS_VARIANT_OF,Bars radar family,1.0,The second member of the Bars radar family is ...
7,Bars radar (N011),HAS_MAX_TRACK_TARGETS_SUBSEQUENT_UPGRADE,15,1.0,This was subsequently upgraded to tracking 15 ...
8,Bars radar (N011),HAS_AIR_TO_AIR_DETECTION_RANGE_INTERCEPT_ROLE_...,65 km,1.0,and 65 km tail-on
9,Rezonans-NE radar,LOCATED_IN_LOCATION,Shoyna (Arctic),1.0,"constructed in the Arctic in Zapolyarniy, Indi..."
10,Irbis-E,IS_A,radar system,1.0,Russian fighter jet radar Irbis-E ... is a Rus...
11,Tikhomirov NIIP,MANUFACTURED_BY,radar system,1.0,... developed by Tikhomirov NIIP for the Sukho...
12,Bars radar beam positioning speed,CAPABILITY_SPEED,positioning beams in 400 microseconds,1.0,capable of positioning beams in 400 microsecon...
13,Bars radar,HAS_CAPABILITY,detect ground and naval based moving targets,1.0,The radar is capable of detecting ground and n...
14,VVS (Russian Air Force),OPERATES_RADAR_SYSTEM,Nebo-M radars,1.0,"The VVS operates several Nebo-M radars, that c..."
15,Rezonans-NE radar,UNDER_CONSTRUCTION_AT_LOCATION,Gremikha,1.0,with another in Gremikha under construction.
16,Bars radar (N011),HAS_MAX_ENGAGE_TARGETS_ORIGINAL_CONFIGURATION,4,1.0,The original requirement... proved impossible ...
17,Bars radar (N011),HAS_MAX_TRACK_TARGETS_UPGRADED_SPECIFICATION,13,1.0,the N011 is still able to simultaneously track...
18,Bars radar (N011),HAS_AIR_TO_AIR_DETECTION_RANGE_INTERCEPT_ROLE_...,140 km,1.0,"when used for intercepting role, the range aga..."
19,Rezonans-NE radar,LOCATED_IN_LOCATION,Nova Zemlya (Arctic),1.0,"constructed in the Arctic in Zapolyarniy, Indi..."
20,Rezonans-NE radar,LOCATED_IN_LOCATION,Zapolyarniy (Arctic),1.0,"constructed in the Arctic in Zapolyarniy, Indi..."
21,Rezonans-NE radar,LOCATED_IN_LOCATION,Indiga (Arctic),1.0,"constructed in the Arctic in Zapolyarniy, Indi..."
22,EL/M-2052,TYPE_OF_SYSTEM,radar system,1.0,
23,Mobile Sector Radar Complex MS RLC,DISPLAYED_AT_EVENT,ARMY-2018 FORUM,1.0,MOBILE SECTOR RADAR COMPLEX MS RLC AT THE ARMY...
24,MiG-29 (Iran),HAS_SENSOR,N019 Rubin radar,1.0,The Iranian MiG-29s are equipped with Soviet N...
25,2457th Air Base of Long Range Radiolocation De...,HAS_SENSOR_PLATFORMS,['A-50'],1.0,Operates A-50 early warning and control aircra...
26,Patriot missile launchers,COMBINED_WITH,elements from existing Ukrainian air defenses ...,1.0,Patriot missile launchers combined with elemen...
27,N011M radar,HAS_PEAK_POWER_OUTPUT,4-5 kW,1.0,The radar has a peak power output of 4-5 kW
28,Malaysian MiG-29 avionics suite,HAS_MODIFICATION,upgraded radar,1.0,...and more capable avionics (including an upg...
29,Voronezh radar,LOCATED_IN,Lekhtusi,1.0,Early warning of missile attack: Voronezh rada...
30,RT-70 radar,LOCATED_IN,Yevpatoria,1.0,(since its annexation by the Russian Federatio...
31,Bars radar,HAS_MAX_TRACK_TARGETS_ORIGINAL_SPECIFICATION,20,1.0,The original requirement to simultaneously tra...
32,MiG-29,HAS_SENSOR,N019MP radar,1.0,Equipped with N019MP radar and an advanced fir...
33,Krona radar,LOCATED_IN,Zelenchukskaya,1.0,... and Krona in Zelenchukskaya ... Space surv...
34,Bars radar (N011),HAS_MAX_ENGAGE_TARGETS_SUBSEQUENT_UPGRADE,6,1.0,This was subsequently upgraded to tracking 15 ...
35,MiG-29K,HAS_RADAR_SIGNATURE_REDUCTION_TECHNOLOGY,radar absorbing coatings,1.0,The MiG-29K has radar absorbing coatings to re...
36,BARS,PART_OF,Russian radars,1.0,The text categorizes it under Russian radars.
37,Zhuk,HAS_CAPABILITY,X band pulse-Doppler radar,1.0,The Zhuk (Beetle) family of X band pulse-Doppl...
38,Ukrainian Air Force anti-aircraft artillery an...,CONDUCTS_MANEUVER_FREQUENCY_CHANGE,"Redeployment maneuvers, 50 involving redeploym...",1.0,
39,Ukrainian Air Force anti-aircraft artillery an...,CONDUCTS_MANEUVER_FREQUENCY_CHANGE_ALTERNATIVE_2,"Redeployment maneuvers, 50 involving redeploym...",1.0,
40,Nebo-UM radar,DELIVERED_TO_LOCATION,Voronezh (2018),1.0,first units were delivered in 2018 to Voronezh...
41,Ukrainian Air Force anti-aircraft artillery an...,CONDUCTS_MANEUVER_FREQUENCY_CHANGE_ALTERNATIVE,"Redeployment maneuvers, 50 involving redeploym...",1.0,
42,Oren Liebermann,HAS_ARTICLE_TITLED,Pentagon acknowledges sending previously undis...,1.0,"Liebermann, Oren (8 August 2022). 'Pentagon ac..."
43,Nebo-UM radar,DELIVERED_TO_LOCATION,Rostov-on-Don (2020),1.0,first units were delivered in 2018 to Voronezh...
44,N-019,REPLACES_WITH_SUBSYSTEM,Phazatron Zhuk-M radar,1.0,retrofitting the aircraft with upgraded avioni...
45,MiG-29UPG,HAS_SENSOR,Zhuk-M radar,1.0,"It includes Zhuk-M radar, new avionics..."
46,Zhuk (radar),TESTED_IN_YEAR,1987,1.0,first tested in 1987...
47,Saab 340 AEW aircraft,HAS_SENSOR_TYPE,AIRBORNE_EARLY_WARNING_AIRCRAFT,1.0,Described as airborne early warning (AEW) airc...
48,MiG-29OVT,HAS_SENSOR,thrust_vectoring_engine_system,1.0,later received thrust vectoring engine and fly...
49,N035 radar,HAS_RANGE,excess of 90 km,1.0,s in excess of 90 km.

,subject,predicate,object,confidence,evidence
0,Bars radar family,CONTAINS_RADAR_MODEL,N035 Irbis-E,1.0,The most powerful radar of Bars radar family
1,Bars radar MAP MODE,HAS_RESOLUTION_LIMITATION,10 meters,1.0,with a maximum resolution of 10 meters
2,Bars radar,HAS_AIR_TO_AIR_DETECTION_RANGE_EARLY_WARNING_ROLE,over 400 km,1.0,The maximum air-to-air detection range is over...
3,Bars radar,HAS_AIR_TO_SURFACE_MODES_COUNT,five air-to-ground modes and four maritime modes,1.0,"For air-to-surface mode, the N011 has five air..."
4,N011M,IS_A,Bars radar family member,1.0,second member of the Bars radar family is the ...
5,Bars radar,HAS_MODE,"mapping mode using real beam, doppler beam sha...",1.0,Bars also features a mapping mode using either...
6,N011M,IS_VARIANT_OF,Bars radar family,1.0,The second member of the Bars radar family is ...
7,Bars radar (N011),HAS_MAX_TRACK_TARGETS_SUBSEQUENT_UPGRADE,15,1.0,This was subsequently upgraded to tracking 15 ...
8,Bars radar (N011),HAS_AIR_TO_AIR_DETECTION_RANGE_INTERCEPT_ROLE_...,65 km,1.0,and 65 km tail-on
9,Rezonans-NE radar,LOCATED_IN_LOCATION,Shoyna (Arctic),1.0,"constructed in the Arctic in Zapolyarniy, Indi..."
10,Irbis-E,IS_A,radar system,1.0,Russian fighter jet radar Irbis-E ... is a Rus...
11,Tikhomirov NIIP,MANUFACTURED_BY,radar system,1.0,... developed by Tikhomirov NIIP for the Sukho...
12,Bars radar beam positioning speed,CAPABILITY_SPEED,positioning beams in 400 microseconds,1.0,capable of positioning beams in 400 microsecon...
13,Bars radar,HAS_CAPABILITY,detect ground and naval based moving targets,1.0,The radar is capable of detecting ground and n...
14,VVS (Russian Air Force),OPERATES_RADAR_SYSTEM,Nebo-M radars,1.0,"The VVS operates several Nebo-M radars, that c..."
15,Rezonans-NE radar,UNDER_CONSTRUCTION_AT_LOCATION,Gremikha,1.0,with another in Gremikha under construction.
16,Bars radar (N011),HAS_MAX_ENGAGE_TARGETS_ORIGINAL_CONFIGURATION,4,1.0,The original requirement... proved impossible ...
17,Bars radar (N011),HAS_MAX_TRACK_TARGETS_UPGRADED_SPECIFICATION,13,1.0,the N011 is still able to simultaneously track...
18,Bars radar (N011),HAS_AIR_TO_AIR_DETECTION_RANGE_INTERCEPT_ROLE_...,140 km,1.0,"when used for intercepting role, the range aga..."
19,Rezonans-NE radar,LOCATED_IN_LOCATION,Nova Zemlya (Arctic),1.0,"constructed in the Arctic in Zapolyarniy, Indi..."
20,Rezonans-NE radar,LOCATED_IN_LOCATION,Zapolyarniy (Arctic),1.0,"constructed in the Arctic in Zapolyarniy, Indi..."
21,Rezonans-NE radar,LOCATED_IN_LOCATION,Indiga (Arctic),1.0,"constructed in the Arctic in Zapolyarniy, Indi..."
22,EL/M-2052,TYPE_OF_SYSTEM,radar system,1.0,
23,Mobile Sector Radar Complex MS RLC,DISPLAYED_AT_EVENT,ARMY-2018 FORUM,1.0,MOBILE SECTOR RADAR COMPLEX MS RLC AT THE ARMY...
24,MiG-29 (Iran),HAS_SENSOR,N019 Rubin radar,1.0,The Iranian MiG-29s are equipped with Soviet N...
25,2457th Air Base of Long Range Radiolocation De...,HAS_SENSOR_PLATFORMS,['A-50'],1.0,Operates A-50 early warning and control aircra...
26,Patriot missile launchers,COMBINED_WITH,elements from existing Ukrainian air defenses ...,1.0,Patriot missile launchers combined with elemen...
27,N011M radar,HAS_PEAK_POWER_OUTPUT,4-5 kW,1.0,The radar has a peak power output of 4-5 kW
28,Malaysian MiG-29 avionics suite,HAS_MODIFICATION,upgraded radar,1.0,...and more capable avionics (including an upg...
29,Voronezh radar,LOCATED_IN,Lekhtusi,1.0,Early warning of missile attack: Voronezh rada...
30,RT-70 radar,LOCATED_IN,Yevpatoria,1.0,(since its annexation by the Russian Federatio...
31,Bars radar,HAS_MAX_TRACK_TARGETS_ORIGINAL_SPECIFICATION,20,1.0,The original requirement to simultaneously tra...
32,MiG-29,HAS_SENSOR,N019MP radar,1.0,Equipped with N019MP radar and an advanced fir...
33,Krona radar,LOCATED_IN,Zelenchukskaya,1.0,... and Krona in Zelenchukskaya ... Space surv...
34,Bars radar (N011),HAS_MAX_ENGAGE_TARGETS_SUBSEQUENT_UPGRADE,6,1.0,This was subsequently upgraded to tracking 15 ...
35,MiG-29K,HAS_RADAR_SIGNATURE_REDUCTION_TECHNOLOGY,radar absorbing coatings,1.0,The MiG-29K has radar absorbing coatings to re...
36,BARS,PART_OF,Russian radars,1.0,The text categorizes it under Russian radars.
37,Zhuk,HAS_CAPABILITY,X band pulse-Doppler radar,1.0,The Zhuk (Beetle) family of X band pulse-Doppl...
38,Ukrainian Air Force anti-aircraft artillery an...,CONDUCTS_MANEUVER_FREQUENCY_CHANGE,"Redeployment maneuvers, 50 involving redeploym...",1.0,
39,Ukrainian Air Force anti-aircraft artillery an...,CONDUCTS_MANEUVER_FREQUENCY_CHANGE_ALTERNATIVE_2,"Redeployment maneuvers, 50 involving redeploym...",1.0,
40,Nebo-UM radar,DELIVERED_TO_LOCATION,Voronezh (2018),1.0,first units were delivered in 2018 to Voronezh...
41,Ukrainian Air Force anti-aircraft artillery an...,CONDUCTS_MANEUVER_FREQUENCY_CHANGE_ALTERNATIVE,"Redeployment maneuvers, 50 involving redeploym...",1.0,
42,Oren Liebermann,HAS_ARTICLE_TITLED,Pentagon acknowledges sending previously undis...,1.0,"Liebermann, Oren (8 August 2022). 'Pentagon ac..."
43,Nebo-UM radar,DELIVERED_TO_LOCATION,Rostov-on-Don (2020),1.0,first units were delivered in 2018 to Voronezh...
44,N-019,REPLACES_WITH_SUBSYSTEM,Phazatron Zhuk-M radar,1.0,retrofitting the aircraft with upgraded avioni...
45,MiG-29UPG,HAS_SENSOR,Zhuk-M radar,1.0,"It includes Zhuk-M radar, new avionics..."
46,Zhuk (radar),TESTED_IN_YEAR,1987,1.0,first tested in 1987...
47,Saab 340 AEW aircraft,HAS_SENSOR_TYPE,AIRBORNE_EARLY_WARNING_AIRCRAFT,1.0,Described as airborne early warning (AEW) airc...
48,MiG-29OVT,HAS_SENSOR,thrust_vectoring_engine_system,1.0,later received thrust vectoring engine and fly...
49,N035 radar,HAS_RANGE,excess of 90 km,1.0,s in excess of 90 km.

In [12]:
show('''
MATCH (subject:Entity)-[fact:FACT]->(object:Entity)
WHERE lower(subject.name) CONTAINS 'mig-29'
   OR lower(object.name) CONTAINS 'mig-29'
   OR lower(subject.name) CONTAINS 'air force'
   OR lower(object.name) CONTAINS 'air force'
RETURN subject.name AS subject, fact.predicate AS predicate, object.name AS object,
       fact.confidence AS confidence, fact.evidence AS evidence
ORDER BY confidence DESC
LIMIT 50
''')

,subject,predicate,object,confidence,evidence
0,MiG-29K,HAS_MISSION,navalised operations,1.0,the navalised Mikoyan MiG-29K
1,MiG-29/35 variants,COUNT_IN_SERVICE_YEARS_2026,728,1.0,As of 2026 an estimated 728 MiG-29/35 variants...
2,Mikoyan-MiG,OPERATED_BY,Soviet Air Forces,1.0,"ration of the Soviet Union, most of the MiG-29..."
3,Russian Naval Aviation,HAS_AIRCRAFT_VARIANT,MiG-29K,1.0,A Russian Naval Aviation MiG-29K... Main artic...
4,MiG-29,OPERATED_BY_COUNTY,more than 30 nations,1.0,more than 30 nations either operate or have op...
5,Indian MiG-29 fleet maintenance issue,BASED_AT,Russia,1.0,India sent the first six of its aircraft to Ru...
6,Ukrainian Air Force,OPERATED_BY,Ukraine,1.0,Article title implies ownership by the state
7,Mikoyan MiG-29,ALSO_KNOWN_AS,Fulcrum,1.0,"""NATO reporting name : Fulcurm"""
8,Mikoyan MiG-29,HAS_CAPABILITY,multirole fighter,1.0,many MiG-29s have been furnished as multirole ...
9,MiG-29M,HAS_WEAPON_COMPATIBILITY_WITH,MiG-29K,1.0,It has a full range of weapons compatible with...
10,MiG-29,OPERATED_BY,Russian Aerospace Forces,1.0,the largest of them being the Russian Aerospac...
11,Serbia Serbian Air Force and Air Defence,INVENTORY_OF,MiG-29SMT,1.0,5 are modernized to the advanced MiG-29SMT sta...
12,Russian Air Force,OPERATED_BY,Russia,1.0,Referenced as 'n air force MiG-29 fleet' and '...
13,MiG-29SM,MANUFACTURED_BY_OR_UPGRADED_BY,Russia,1.0,Syrian MiG-29SM fighters (a deep upgrade by Ru...
14,Mikoyan MiG-29UB,VARIANT_OF,MiG-29,1.0,four twin-seat MiG-29UBs were part of the init...
15,Mikoyan MiG-29,USED_IN,Syria,1.0,Russia Has Deployed Its MiG-29SMT Multirole Co...
16,MiG-29UPG upgrade provider (first batch),MANUFACTURED_BY_UPGRADE_LOCATION,Russia,1.0,the first six MiG-29s were to be upgraded in R...
17,Mikoyan MiG-29,ALSO_KNOWN_AS,Fulcrum,1.0,referred to as Ukrainian Mig-29 Fulcrum in dis...
18,Kbely Air Museum,EXHIBITS,Mikoyan MiG-29,1.0,
19,Mikoyan MiG-29,DESIGNED_IN,Soviet Union,1.0,"""twin-engine fighter aircraft designed in the ..."
20,MiG-29,ALSO_KNOWN_AS,Mikoyan MiG-29,1.0,
21,Mikoyan MiG-29,HAS_ROLE,air superiority fighter,1.0,"""Developed by the Mikoyan design bureau as an ..."
22,Mikoyan MiG-29,ENTERED_SERVICE_WITH,Soviet Air Forces,1.0,"""The MiG-29 entered service with the Soviet Ai..."
23,Russian Air Force,MERGED_INTO_ON_DATE,Russian Aerospace Forces,1.0,"On 1 August 2015, the Russian Air Force... wer..."
24,MiG-29,DEPLOYED_TO,Ukraine,1.0,
25,MiG-29SE,MANUFACTURED_BY,Mikoyan,1.0,Peru contracted RAC MiG to overhaul and upgrad...
26,MiG-29s,MANUFACTURED_BY,Mikoyan,1.0,
27,Mikoyan MiG-29,HAS_OPERATOR,Syria,1.0,Turkey shot down a Syrian MiG-29 on 14 Novembe...
28,Mikoyan MiG-29,ALSO_KNOWN_AS,MiG-29,1.0,"""The Mikoyan MiG-29 ... is a twin-engine fight..."
29,Zhuk-MA target aircraft types,DESIGNED_FOR_AIRCRAFT_TYPE,MiG-29,1.0,Was aimed for Su-27's and MiG-29's.
30,Bars-29,PLATFORM_OF_DESIGNATION,MiG-29,1.0,modified N011M radar for the MiG-29 designated...
31,Russia,MANUFACTURED_BY,Mikoyan MiG-29,1.0,
32,MiG-29,USED_IN,Russian invasion of Ukraine,1.0,
33,Russian Aerospace Forces,OPERATED_BY_UNIT_TYPE,Mikoyan MiG-29,1.0,operates 278 Mikoyan MiG-29s as of 2026
34,MiG-29SMT,CONFIGURATION_OF,MiG-29,1.0,upgrade its existing fleet to the modernised M...
35,VVS (Russian Air Force),DEPLOYED_TO,Ukraine,1.0,
36,MiG-29,DEPLOYED_TO,Syria,1.0,
37,Syrian Air Force,OPERATED_BY,Syria,1.0,remaining assets of the SyAAF...
38,MiG-29K/KUB,VARIANT_OF,MiG-29,1.0,
39,Peruvian Air Force,OPERATES,MiG-29,1.0,Peruviam Fulcrum - FlightGlobal; Peruvian MiG-...
40,Ukrainian Air Force (post-February 2022),ENGAGED_IN_COMBAT_OPERATIONS,Russian invasion of Ukraine,1.0,"Since February 2022, the Air Force has been en..."
41,Mikoyan MiG-29,HAS_ENGINE_COUNT,twin-engine,1.0,"""Soviet twin-engine jet fighter aircraft"""
42,Kazakhstan,RETIRED_FROM_SERVICE,MiG-29,1.0,These were retired in 2023.
43,Kazakh Air and Air Defence Forces,OPERATED_BY,MiG-29,1.0,23 MiG-29s as of 2023.
44,Russian Air Force,GROUNDED_ALL_OF_MODEL,MiG-29,1.0,The Russian Air Force grounded all its MiG-29s...
45,Mikoyan MiG-29,MANUFACTURED_BY,Mikoyan Design Bureau,1.0,"""Developed by the Mikoyan design bureau"""
46,Reptár - Szolnoki repülőmúzeum,DISPENSES_EXHIBITION_OF,Mikoyan MiG-29,1.0,
47,Mikoyan MiG-29SMT,DEPLOYED_TO,Syria,1.0,Russia Has Deployed Its MiG-29SMT Multirole Co...
48,Ukraine,OPERATED_BY,MiG-29,1.0,Ukrainian MiG-29s were used by several brigade...
49,MiG-29/35 fleet global rank_2026,GLOBAL_RANK_FLEET_SIZE_YEARS_2026,sixth largest fleet,1.0,representing the sixth largest fleet and 5% of...

,subject,predicate,object,confidence,evidence
0,MiG-29K,HAS_MISSION,navalised operations,1.0,the navalised Mikoyan MiG-29K
1,MiG-29/35 variants,COUNT_IN_SERVICE_YEARS_2026,728,1.0,As of 2026 an estimated 728 MiG-29/35 variants...
2,Mikoyan-MiG,OPERATED_BY,Soviet Air Forces,1.0,"ration of the Soviet Union, most of the MiG-29..."
3,Russian Naval Aviation,HAS_AIRCRAFT_VARIANT,MiG-29K,1.0,A Russian Naval Aviation MiG-29K... Main artic...
4,MiG-29,OPERATED_BY_COUNTY,more than 30 nations,1.0,more than 30 nations either operate or have op...
5,Indian MiG-29 fleet maintenance issue,BASED_AT,Russia,1.0,India sent the first six of its aircraft to Ru...
6,Ukrainian Air Force,OPERATED_BY,Ukraine,1.0,Article title implies ownership by the state
7,Mikoyan MiG-29,ALSO_KNOWN_AS,Fulcrum,1.0,"""NATO reporting name : Fulcurm"""
8,Mikoyan MiG-29,HAS_CAPABILITY,multirole fighter,1.0,many MiG-29s have been furnished as multirole ...
9,MiG-29M,HAS_WEAPON_COMPATIBILITY_WITH,MiG-29K,1.0,It has a full range of weapons compatible with...
10,MiG-29,OPERATED_BY,Russian Aerospace Forces,1.0,the largest of them being the Russian Aerospac...
11,Serbia Serbian Air Force and Air Defence,INVENTORY_OF,MiG-29SMT,1.0,5 are modernized to the advanced MiG-29SMT sta...
12,Russian Air Force,OPERATED_BY,Russia,1.0,Referenced as 'n air force MiG-29 fleet' and '...
13,MiG-29SM,MANUFACTURED_BY_OR_UPGRADED_BY,Russia,1.0,Syrian MiG-29SM fighters (a deep upgrade by Ru...
14,Mikoyan MiG-29UB,VARIANT_OF,MiG-29,1.0,four twin-seat MiG-29UBs were part of the init...
15,Mikoyan MiG-29,USED_IN,Syria,1.0,Russia Has Deployed Its MiG-29SMT Multirole Co...
16,MiG-29UPG upgrade provider (first batch),MANUFACTURED_BY_UPGRADE_LOCATION,Russia,1.0,the first six MiG-29s were to be upgraded in R...
17,Mikoyan MiG-29,ALSO_KNOWN_AS,Fulcrum,1.0,referred to as Ukrainian Mig-29 Fulcrum in dis...
18,Kbely Air Museum,EXHIBITS,Mikoyan MiG-29,1.0,
19,Mikoyan MiG-29,DESIGNED_IN,Soviet Union,1.0,"""twin-engine fighter aircraft designed in the ..."
20,MiG-29,ALSO_KNOWN_AS,Mikoyan MiG-29,1.0,
21,Mikoyan MiG-29,HAS_ROLE,air superiority fighter,1.0,"""Developed by the Mikoyan design bureau as an ..."
22,Mikoyan MiG-29,ENTERED_SERVICE_WITH,Soviet Air Forces,1.0,"""The MiG-29 entered service with the Soviet Ai..."
23,Russian Air Force,MERGED_INTO_ON_DATE,Russian Aerospace Forces,1.0,"On 1 August 2015, the Russian Air Force... wer..."
24,MiG-29,DEPLOYED_TO,Ukraine,1.0,
25,MiG-29SE,MANUFACTURED_BY,Mikoyan,1.0,Peru contracted RAC MiG to overhaul and upgrad...
26,MiG-29s,MANUFACTURED_BY,Mikoyan,1.0,
27,Mikoyan MiG-29,HAS_OPERATOR,Syria,1.0,Turkey shot down a Syrian MiG-29 on 14 Novembe...
28,Mikoyan MiG-29,ALSO_KNOWN_AS,MiG-29,1.0,"""The Mikoyan MiG-29 ... is a twin-engine fight..."
29,Zhuk-MA target aircraft types,DESIGNED_FOR_AIRCRAFT_TYPE,MiG-29,1.0,Was aimed for Su-27's and MiG-29's.
30,Bars-29,PLATFORM_OF_DESIGNATION,MiG-29,1.0,modified N011M radar for the MiG-29 designated...
31,Russia,MANUFACTURED_BY,Mikoyan MiG-29,1.0,
32,MiG-29,USED_IN,Russian invasion of Ukraine,1.0,
33,Russian Aerospace Forces,OPERATED_BY_UNIT_TYPE,Mikoyan MiG-29,1.0,operates 278 Mikoyan MiG-29s as of 2026
34,MiG-29SMT,CONFIGURATION_OF,MiG-29,1.0,upgrade its existing fleet to the modernised M...
35,VVS (Russian Air Force),DEPLOYED_TO,Ukraine,1.0,
36,MiG-29,DEPLOYED_TO,Syria,1.0,
37,Syrian Air Force,OPERATED_BY,Syria,1.0,remaining assets of the SyAAF...
38,MiG-29K/KUB,VARIANT_OF,MiG-29,1.0,
39,Peruvian Air Force,OPERATES,MiG-29,1.0,Peruviam Fulcrum - FlightGlobal; Peruvian MiG-...
40,Ukrainian Air Force (post-February 2022),ENGAGED_IN_COMBAT_OPERATIONS,Russian invasion of Ukraine,1.0,"Since February 2022, the Air Force has been en..."
41,Mikoyan MiG-29,HAS_ENGINE_COUNT,twin-engine,1.0,"""Soviet twin-engine jet fighter aircraft"""
42,Kazakhstan,RETIRED_FROM_SERVICE,MiG-29,1.0,These were retired in 2023.
43,Kazakh Air and Air Defence Forces,OPERATED_BY,MiG-29,1.0,23 MiG-29s as of 2023.
44,Russian Air Force,GROUNDED_ALL_OF_MODEL,MiG-29,1.0,The Russian Air Force grounded all its MiG-29s...
45,Mikoyan MiG-29,MANUFACTURED_BY,Mikoyan Design Bureau,1.0,"""Developed by the Mikoyan design bureau"""
46,Reptár - Szolnoki repülőmúzeum,DISPENSES_EXHIBITION_OF,Mikoyan MiG-29,1.0,
47,Mikoyan MiG-29SMT,DEPLOYED_TO,Syria,1.0,Russia Has Deployed Its MiG-29SMT Multirole Co...
48,Ukraine,OPERATED_BY,MiG-29,1.0,Ukrainian MiG-29s were used by several brigade...
49,MiG-29/35 fleet global rank_2026,GLOBAL_RANK_FLEET_SIZE_YEARS_2026,sixth largest fleet,1.0,representing the sixth largest fleet and 5% of...

## 7. Equivalent CLI command

The same module is also exposed by the repository CLI. This notebook form is useful for iterative review, while the command below is better for repeatable batch runs.

In [ ]:
cli = [
    'python -m combat_id_calibration ingest-graph',
    f'  --neo4j-uri {NEO4J_URI}',
    f'  --neo4j-user {NEO4J_USER}',
    '  --neo4j-password "$NEO4J_PASSWORD"',
    f'  --facts-jsonl {FACTS_JSONL}',
    f'  --model {MODEL}',
    f'  --ollama-url {OLLAMA_URL}',
    *[f'  --wikipedia {url}' for url in WIKIPEDIA_URLS],
]
print(' \
'.join(cli))